
# OC
use_frameworks!
target 'ArchitectGabriellaiOS' do
pod 'Reveal-SDK', :configurations => ['Debug']
# pod 'ReactiveObjC'
pod 'JSONModel'
pod 'AFNetworking'
pod 'SDWebImage'
pod 'MBProgressHUD'
pod 'ViewDeck'
pod 'MJRefresh'
pod 'SVProgressHUD'
pod 'MJExtension'
pod 'MMDrawerController'
pod 'Masonry'
#pod 'BaiduMapKit'
end

